env:
  global:
  - secure: B5TnUWMjgOemv2U8ZIt70s3j1nAj8SVVdk5yfQfHy8tKsNbtUvVd8LgQXcuX+vR6p8WpkDQLUwcq1PaR6laYafTa41/UYXVQ3Zc9Xei/s25A/q5YjpZ1RSCZlA6YfQ5AfyEhxe/Se2GQ4qohF5WKazhk3vkpa52KO64MXRj6MjE=
  - secure: JoqtOoJzLwQtc4HXohwgOVDNZNOaBc+242wPci9ZLQSsOGU3M1S7C60o5npt1zn4+YXCK9cTg2AqD7bED9WLOKUUDfAENq8CjNyQI04AqC+6sEqAZzBSZGR3fuStjcBt9+hXqe/yOI7YWAIntW0TAsoGAWNrs44SuY9y4i4aH7k=
  - secure: hazKMhnma5IeEW0IZV9haDi6wjQgXHYFGZsxlpg6px8mvnQSmPN/cxirBuz3pW43ok8q6dB49AjxFGjekFkrnMpbzVl4vfYkoUe/Xhj5KO5VIgFNC1y9QHo/6Cfw4a1G+ph8e+/IYXOOgLbwr1MsUiYZCxLxG7QwbwLp27ahJO0=
language: java
jdk:
- oraclejdk7
install:
- sudo apt-get update -y
- chmod +x ./gradlew
script:
- "./gradlew build"
notifications:
 irc:
  channels:
   - "irc.esper.net#Disconsented "
  template:
   - "%{build_number} (%{branch} - %{commit}: %{commit_message} : %{author}): %{message} (%{build_url}) "
deploy:
  provider: releases
  api_key:
    secure: VhPE7D1RUg5NVYN5NijQElRCBXcwG4GLFIv3Tl4OdShL2/V8VkCn8FgNnvIsYPR2J95QfYkmop2H2Fjxztni/tF8hun5qS+VAzgVjE8mep53NQ4VsfkVGcHQAMsjqELe3njGeecZs8RI2cxhPSBexvlBflakhi1cq2GlYEaeBeY=
  file: "/build/libs/*.jar"
  on:
    repo: disconsented/ANSSRPG
    branch: master