language: java
jdk:
- oraclejdk7
cache:
  directories:
    - $HOME/.gradle
    - .gradle
sudo: false
install: true
branches:
  only:
    - master
    - build
script:
  - gradle build --stacktrace
notifications:
 irc:
  channels:
   - "irc.esper.net#Disconsented "
  template:
   - "%{build_number} (%{branch} - %{commit}: %{commit_message} : %{author}): %{message} (%{build_url}) "
   
before_deploy:
  - "echo 'Attempting to deploy'"
  - ls ./build/libs/
  - gradle tagRelease -Pusr=USER -Ppwd=PASS
deploy:
  provider: releases
  api_key:
    secure: VhPE7D1RUg5NVYN5NijQElRCBXcwG4GLFIv3Tl4OdShL2/V8VkCn8FgNnvIsYPR2J95QfYkmop2H2Fjxztni/tF8hun5qS+VAzgVjE8mep53NQ4VsfkVGcHQAMsjqELe3njGeecZs8RI2cxhPSBexvlBflakhi1cq2GlYEaeBeY=
  file_glob: true
  file: ./build/libs/*.jar
  skip_cleanup: true
  on:
    repo: disconsented/ANSSRPG
    all_branches: true
